version: '3.8'

services:
    mariadb:
        container_name: mariadb
        build: requirements/mariadb
        image: mariadb
        restart: on-failure
        env_file:
            - .env
        volumes:
            - DB:/var/lib/mysql
        networks:
            - inception-network

    wordpress:
        container_name: wordpress
        build: requirements/wordpress
        image: wordpress
        restart: on-failure
        env_file:
            - .env
        volumes:
            - wordpress:/var/www/html
        networks:
            - inception-network
    
    nginx:
        depends_on :
            - wordpress
        container_name: nginx
        build: requirements/nginx
        image: nginx
        restart: on-failure
        ports:
            - 443:443
        env_file:
            - .env
        volumes:
            - wordpress:/var/www/html
        networks:
            - inception-network

volumes:
    DB:
        name: database
        driver: local
        driver_opts:
            type: none
            o: bind
            device: /home/mmoumani/data/db/
    wordpress:
        name: wordpress
        driver: local
        driver_opts:
            type: none
            o: bind
            device: /home/mmoumani/data/wordpress/

networks:
    inception-network:
        name: inception-network