version: '3.8'

services:
    mariadb:
        container_name: mariadb
        build: requirements/mariadb
        restart: on-failure
        ports:
            - 3306:3306
        env_file:
            - .env
        volumes:
            - DB:/var/lib/mysql
        networks:
            - network

    wordpress:
        depends_on:
            - mariadb
        container_name: wordpress
        build: requirements/wordpress
        restart: on-failure
        ports:
            - 9000:9000
        env_file:
            - .env
        volumes:
            - wordpress:/var/www/html
        networks:
            - network
    
    nginx:
        depends_on :
            - wordpress
        container_name: nginx
        build: requirements/nginx
        restart: on-failure
        ports:
            - 443:443
        env_file:
            - .env
        volumes:
            - wordpress:/var/www/html
        networks:
            - network

volumes:
    DB:
        name: database
        # driver: local
        # driver_opts:
        #     type: none
        #     o: bind
        #     device: /Users/mmoumani/Desktop/data/database
    wordpress:
        name: wordpress

networks:
  network:
    name: network
    # driver: bridge # The default network
