# FROM nginx:1.10.1-alpine
# FROM debian:stable
# FROM wordpress:latest
# RUN apt-get -y update && apt-get -y install nginx
FROM debian:stable
COPY src/html /var/www/html
# COPY src/html /usr/share/nginx/html
# COPY default /etc/nginx/sites-available/default
# EXPOSE 80/tcp